export const countryCodes = [
  { code: "+258", flag: "🇲🇿", name: "Moçambique" },
  { code: "+244", flag: "🇦🇴", name: "Angola" },
  { code: "+238", flag: "🇨🇻", name: "Cabo Verde" },
  { code: "+240", flag: "🇬🇶", name: "Guiné Equatorial" },
  { code: "+245", flag: "🇬🇼", name: "Guiné-Bissau" },
  { code: "+239", flag: "🇸🇹", name: "São Tomé e Príncipe" },
  { code: "+27", flag: "🇿🇦", name: "África do Sul" },
  { code: "+234", flag: "🇳🇬", name: "Nigéria" },
  { code: "+254", flag: "🇰🇪", name: "Quénia" },
  { code: "+251", flag: "🇪🇹", name: "Etiópia" },
  { code: "+20", flag: "🇪🇬", name: "Egito" },
  { code: "+212", flag: "🇲🇦", name: "Marrocos" },
  { code: "+216", flag: "🇹🇳", name: "Tunísia" },
  { code: "+233", flag: "🇬🇭", name: "Gana" },
  { code: "+255", flag: "🇹🇿", name: "Tanzânia" },
  { code: "+256", flag: "🇺🇬", name: "Uganda" },
  { code: "+225", flag: "🇨🇮", name: "Costa do Marfim" },
  { code: "+221", flag: "🇸🇳", name: "Senegal" },
  { code: "+223", flag: "🇲🇱", name: "Mali" },
  { code: "+226", flag: "🇧🇫", name: "Burkina Faso" },
  { code: "+227", flag: "🇳🇪", name: "Níger" },
  { code: "+228", flag: "🇹🇬", name: "Togo" },
  { code: "+229", flag: "🇧🇯", name: "Benin" },
  { code: "+230", flag: "🇲🇺", name: "Maurícia" },
  { code: "+232", flag: "🇸🇱", name: "Serra Leoa" },
  { code: "+236", flag: "🇨🇫", name: "Rep. Centro-Africana" },
  { code: "+237", flag: "🇨🇲", name: "Camarões" },
  { code: "+241", flag: "🇬🇦", name: "Gabão" },
  { code: "+242", flag: "🇨🇬", name: "Rep. do Congo" },
  { code: "+243", flag: "🇨🇩", name: "Rep. Dem. do Congo" },
  { code: "+247", flag: "🇸🇭", name: "Santa Helena" },
  { code: "+248", flag: "🇸🇨", name: "Seicheles" },
  { code: "+249", flag: "🇸🇩", name: "Sudão" },
  { code: "+250", flag: "🇷🇼", name: "Ruanda" },
  { code: "+253", flag: "🇩🇯", name: "Djibuti" },
  { code: "+257", flag: "🇧🇮", name: "Burundi" },
  { code: "+260", flag: "🇿🇲", name: "Zâmbia" },
  { code: "+263", flag: "🇿🇼", name: "Zimbábue" },
  { code: "+264", flag: "🇳🇦", name: "Namíbia" },
  { code: "+265", flag: "🇲🇼", name: "Malawi" },
  { code: "+266", flag: "🇱🇸", name: "Lesoto" },
  { code: "+267", flag: "🇧🇼", name: "Botswana" },
  { code: "+268", flag: "🇸🇿", name: "Essuatíni" },
  { code: "+269", flag: "🇰🇲", name: "Comores" },
  { code: "+291", flag: "🇪🇷", name: "Eritreia" },
  { code: "+298", flag: "🇫🇴", name: "Ilhas Faroé" },
  { code: "+55", flag: "🇧🇷", name: "Brasil" },
  { code: "+351", flag: "🇵🇹", name: "Portugal" },
  { code: "+1", flag: "🇺🇸", name: "EUA/Canadá" },
  { code: "+34", flag: "🇪🇸", name: "Espanha" },
  { code: "+33", flag: "🇫🇷", name: "França" },
  { code: "+49", flag: "🇩🇪", name: "Alemanha" },
  { code: "+39", flag: "🇮🇹", name: "Itália" },
  { code: "+44", flag: "🇬🇧", name: "Reino Unido" },
  { code: "+52", flag: "🇲🇽", name: "México" },
  { code: "+54", flag: "🇦🇷", name: "Argentina" },
  { code: "+56", flag: "🇨🇱", name: "Chile" },
  { code: "+57", flag: "🇨🇴", name: "Colômbia" },
  { code: "+86", flag: "🇨🇳", name: "China" },
  { code: "+81", flag: "🇯🇵", name: "Japão" },
  { code: "+82", flag: "🇰🇷", name: "Coreia do Sul" },
  { code: "+91", flag: "🇮🇳", name: "Índia" },
  { code: "+61", flag: "🇦🇺", name: "Austrália" },
  { code: "+64", flag: "🇳🇿", name: "Nova Zelândia" },
];